language: java
sudo: required
jdk:
- oraclejdk8
install:
- mvn install -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8
deploy:
  api_key:
    secure: OCd/uwucCuzXpCKcwzZH9gBHCQR+6YGIyVEScj46Ed3uIHCiDi2ZO6nFz1eioQZcxpJ6hrdhc0s/8ItuIrvuvHh+ZKALboXNP9w+7Kn6p4sjSh2v0YZDyBFqdOMu/V3PBRZAOTyzzsOL4T4Qf7K4gA1earWt1M61hHXqdrZW8X+7cAOpkEN9EnhBdrzr0E8y+qz4dNCflkyjg5smmKxcyN9457FiKdt4TcKB52FhknS/qyo/SBQibusjlCtayrjcvYj1CGdoXlLXlHa223QSNTCMP6denOR/VbkGA/SYeyl98OEp+ioIUtYmib5aiek/L0OFaZS6oLSuVdSVHQiIy3XHhIszF7ucvRJiild3LY9KZhLhJ6VXisnzRRBSavsm50Wj8XXDCpIU9t1q7odFnqyyOnCHF1tTfzc1EZ6xFBuYdfgd3XAU0L9Qx0eKtQ6k/gURfftUTclOHh6DvrCg4vmvdOJALd02BoYl8eFZ1Ti7wiovxwVgYWFz65nzu4ImVKxX2CYAKAAl8L5hTi33xb+vie7DHxZOxgOT2oKo3k822J9pc33CxWWuPAnkrenAENNic2Wjq6oyx5/yhJTMSGCP3t9NFoznEdYmKUSCNIzV90kUf3k78M+fYXaes+pWG50+gpivFcTuTqHT05TaGZaGaZaNUKL76SGaGz8GXes=
